import os
import sqlite3

try:
    import psycopg
    from psycopg.errors import IntegrityError as PsycopgIntegrityError
    from psycopg.rows import dict_row
except ImportError:  # pragma: no cover
    psycopg = None
    PsycopgIntegrityError = None
    dict_row = None


DATABASE_URL = os.getenv("DATABASE_URL", "").strip()
USE_POSTGRES = DATABASE_URL.startswith(("postgres://", "postgresql://"))
DATABASE_NAME = os.getenv("DATABASE_NAME", "attendance.db")
POSTGRES_INTEGRITY_ERRORS = (
    (PsycopgIntegrityError,) if PsycopgIntegrityError is not None else ()
)
POSTGRES_DATABASE_ERRORS = (
    (psycopg.Error,) if psycopg is not None else ()
)

if not USE_POSTGRES:
    database_dir = os.path.dirname(DATABASE_NAME)
    if database_dir:
        os.makedirs(database_dir, exist_ok=True)


SQLITE_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS Users (
        user_id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at INTEGER DEFAULT (strftime('%s', 'now'))
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Courses (
        course_id INTEGER PRIMARY KEY AUTOINCREMENT,
        host_id INTEGER NOT NULL,
        name TEXT NOT NULL,
        join_code TEXT NOT NULL UNIQUE,
        geolocation_latitude REAL,
        geolocation_longitude REAL,
        created_at INTEGER DEFAULT (strftime('%s', 'now')),
        late_threshold_minutes INTEGER DEFAULT 10,
        present_threshold_minutes INTEGER DEFAULT 0,
        FOREIGN KEY (host_id) REFERENCES Users(user_id) ON DELETE CASCADE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Enrollments (
        user_id INTEGER NOT NULL,
        course_id INTEGER NOT NULL,
        enrolled_at INTEGER DEFAULT (strftime('%s', 'now')),
        PRIMARY KEY (user_id, course_id),
        FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE,
        FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Sessions (
        session_id INTEGER PRIMARY KEY AUTOINCREMENT,
        course_id INTEGER NOT NULL,
        start_time INTEGER NOT NULL,
        end_time INTEGER,
        FOREIGN KEY (course_id) REFERENCES Courses(course_id) ON DELETE CASCADE
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Attendances (
        attendance_id INTEGER PRIMARY KEY AUTOINCREMENT,
        session_id INTEGER NOT NULL,
        user_id INTEGER NOT NULL,
        status TEXT NOT NULL,
        late_minutes INTEGER,
        user_geolocation_latitude REAL,
        user_geolocation_longitude REAL,
        proof_base64 TEXT,
        joined_at INTEGER DEFAULT (strftime('%s', 'now')),
        UNIQUE (session_id, user_id),
        FOREIGN KEY (session_id) REFERENCES Sessions(session_id) ON DELETE CASCADE,
        FOREIGN KEY (user_id) REFERENCES Users(user_id) ON DELETE CASCADE
    );
    """,
]


POSTGRES_SCHEMA = [
    """
    CREATE TABLE IF NOT EXISTS Users (
        user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        email TEXT NOT NULL UNIQUE,
        password_hash TEXT NOT NULL,
        created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Courses (
        course_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        host_id BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        join_code TEXT NOT NULL UNIQUE,
        geolocation_latitude DOUBLE PRECISION,
        geolocation_longitude DOUBLE PRECISION,
        created_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
        late_threshold_minutes BIGINT DEFAULT 10,
        present_threshold_minutes BIGINT DEFAULT 0
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Enrollments (
        user_id BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
        course_id BIGINT NOT NULL REFERENCES Courses(course_id) ON DELETE CASCADE,
        enrolled_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
        PRIMARY KEY (user_id, course_id)
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Sessions (
        session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        course_id BIGINT NOT NULL REFERENCES Courses(course_id) ON DELETE CASCADE,
        start_time BIGINT NOT NULL,
        end_time BIGINT
    );
    """,
    """
    CREATE TABLE IF NOT EXISTS Attendances (
        attendance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        session_id BIGINT NOT NULL REFERENCES Sessions(session_id) ON DELETE CASCADE,
        user_id BIGINT NOT NULL REFERENCES Users(user_id) ON DELETE CASCADE,
        status TEXT NOT NULL,
        late_minutes BIGINT,
        user_geolocation_latitude DOUBLE PRECISION,
        user_geolocation_longitude DOUBLE PRECISION,
        proof_base64 TEXT,
        joined_at BIGINT DEFAULT (EXTRACT(EPOCH FROM NOW())::BIGINT),
        UNIQUE (session_id, user_id)
    );
    """,
]


def _normalize_query(query):
    if not USE_POSTGRES:
        return query
    return query.replace("?", "%s")


def get_db_connection():
    """Establishes and returns a database connection."""
    if USE_POSTGRES:
        if psycopg is None:
            raise RuntimeError("psycopg is required when DATABASE_URL is set.")
        return psycopg.connect(DATABASE_URL, row_factory=dict_row)

    conn = sqlite3.connect(DATABASE_NAME)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def execute_query(query, params=()):
    """Executes an INSERT, UPDATE, or DELETE query and commits the changes."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(_normalize_query(query), params)
        inserted_id = None

        if cursor.description:
            row = cursor.fetchone()
            if row:
                inserted_id = next(iter(row.values())) if isinstance(row, dict) else row[0]
        elif not USE_POSTGRES:
            inserted_id = cursor.lastrowid

        conn.commit()
        return inserted_id
    except sqlite3.IntegrityError as e:
        raise ValueError(f"Database Integrity Error: {e}")
    except sqlite3.Error as e:
        raise RuntimeError(f"Database Error: {e}")
    except POSTGRES_INTEGRITY_ERRORS as e:
        raise ValueError(f"Database Integrity Error: {e}")
    except Exception as e:
        if USE_POSTGRES and isinstance(e, POSTGRES_DATABASE_ERRORS):
            raise RuntimeError(f"Database Error: {e}")
        raise
    finally:
        conn.close()


def fetch_one(query, params=()):
    """Executes a SELECT query and fetches a single row."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(_normalize_query(query), params)
        return cursor.fetchone()
    except sqlite3.Error as e:
        raise RuntimeError(f"Database Error: {e}")
    except Exception as e:
        if USE_POSTGRES and isinstance(e, POSTGRES_DATABASE_ERRORS):
            raise RuntimeError(f"Database Error: {e}")
        raise
    finally:
        conn.close()


def fetch_all(query, params=()):
    """Executes a SELECT query and fetches all rows."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        cursor.execute(_normalize_query(query), params)
        return cursor.fetchall()
    except sqlite3.Error as e:
        raise RuntimeError(f"Database Error: {e}")
    except Exception as e:
        if USE_POSTGRES and isinstance(e, POSTGRES_DATABASE_ERRORS):
            raise RuntimeError(f"Database Error: {e}")
        raise
    finally:
        conn.close()


def create_tables():
    """Creates all necessary tables in the database if they don't exist."""
    conn = get_db_connection()
    cursor = conn.cursor()
    try:
        schema = POSTGRES_SCHEMA if USE_POSTGRES else SQLITE_SCHEMA
        for statement in schema:
            cursor.execute(statement)
        conn.commit()
    finally:
        conn.close()

    db_target = "postgres" if USE_POSTGRES else DATABASE_NAME
    print(f"Database '{db_target}' and tables created/verified.")


def initialize_db():
    """Initializes the database by creating tables."""
    create_tables()


if __name__ == "__main__":
    initialize_db()
